fix: cve fix for kafka and jmx-javaagent
mesosphere/dkp-catalog-applications pull request #145
Opened 2024-09-13 07:38 UTC by SandhyaRavi2403

CVE fix for Kafka and jmx-javaagent

https://jira.nutanix.com/browse/NCN-102450
https://jira.nutanix.com/browse/NCN-102451

workflow:
https://github.com/mesosphere/dkp-container-images/actions/runs/10844306857

2024-09-17 18:35 UTC, mhrabovcin requested changes
@SandhyaRavi2403 we need keep the kafka `0.25.1` version in the `/services` directory and add the `0.25.2` with image bumps and changes.

2024-09-17 18:51 UTC, SandhyaRavi2403 commented
> @SandhyaRavi2403 we need keep the kafka `0.25.1` version in the `/services` directory and add the `0.25.2` with image bumps and changes.

@mhrabovcin the version is kept as is       version: 0.25.1, wherein the bump is updated. Do you mean not bump, get back to previous one `/services/0.25.1`

2024-09-17 19:00 UTC, mhrabovcin commented
@SandhyaRavi2403 we will end up with 2 directories in the services dir. 0.25.1 and 0.25.2. We need to keep 0.25.1 as it is and add 0.25.2 with image bumps.

2024-09-17 19:05 UTC, msdolbey approved these changes
👍 
![it is though](https://media.tenor.com/eyl3G0lGRvsAAAAM/mulsup-cheesepuffs3000.gif)

2024-09-18 07:26 UTC, mhrabovcin commented on services/kafka-operator/0.25.2/kafka-operator.yaml
> +apiVersion: helm.toolkit.fluxcd.io/v2beta1
```suggestion
apiVersion: helm.toolkit.fluxcd.io/v2beta2
```

2024-09-18 08:16 UTC, mhrabovcin commented
@SandhyaRavi2403 the last commit title needs to be fixed here.

2024-09-18 09:00 UTC, mhrabovcin approved these changes

2024-09-18 09:00 UTC, merged