docs: Add note about installation
mesosphere/dkp-catalog-applications pull request #19
Opened 2022-01-06 20:49 UTC by cbuto

related to https://github.com/mesosphere/dcos-docs-site/pull/4016/files

2022-01-06 21:04 UTC, cwyl02 requested changes

2022-01-06 21:04 UTC, cwyl02 commented on services/zookeeper-operator/metadata.yaml
> +  **Note: Only install the Spark operator once per workspace.**
should be `Zookeeper operator`

2022-01-06 21:08 UTC, cbuto commented on services/zookeeper-operator/metadata.yaml
> +  **Note: Only install the Spark operator once per workspace.**
😅 fixed!

2022-01-06 21:31 UTC, cwyl02 approved these changes

2022-01-07 19:29 UTC, gracedo approved these changes

2022-01-07 19:29 UTC, merged